#!/usr/bin/env bash

groupadd -f netconf

NP2_MODULE_DIR=/usr/share/yang/modules/netopeer2
NP2_MODULE_PERMS=660
NP2_MODULE_OWNER=root
NP2_MODULE_GROUP=netconf

{% include 'scripts/setup.sh' %}
{% include 'scripts/merge_hostkey.sh' %}
{% include 'scripts/merge_config.sh' %}
